# Generated by Django 3.2 on 2021-05-10 12:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierModel',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=5)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None), size=None)),
                ('rating', models.FloatField(null=True)),
                ('earnings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None), size=None)),
                ('courier_salary_coefficient', models.IntegerField(null=True)),
                ('assign_time', models.DateTimeField(null=True)),
                ('complete_time', models.DateTimeField(null=True)),
                ('delivery_time', models.IntegerField(null=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_service.couriermodel')),
            ],
        ),
    ]
