# Generated by Django 3.2 on 2021-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriermodel',
            name='min_delivery_time',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='couriermodel',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
