# Generated by Django 3.2 on 2021-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_service', '0002_auto_20210510_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriermodel',
            name='min_delivery_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='couriermodel',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
